// Code generated by "stringer -type=DataFrameType"; DO NOT EDIT.

package transport

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Request-0]
	_ = x[Response-1]
}

const _DataFrameType_name = "RequestResponse"

var _DataFrameType_index = [...]uint8{0, 7, 15}

func (i DataFrameType) String() string {
	if i >= DataFrameType(len(_DataFrameType_index)-1) {
		return "DataFrameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataFrameType_name[_DataFrameType_index[i]:_DataFrameType_index[i+1]]
}
