// Code generated by "stringer -type=CommandType"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Request-0]
	_ = x[Response-1]
}

const _CommandType_name = "RequestResponse"

var _CommandType_index = [...]uint8{0, 7, 15}

func (i CommandType) String() string {
	if i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
