// Code generated by "stringer -type=CommandID"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GetLibraryVersion-21]
	_ = x[GET_INIT_DATA-2]
	_ = x[SET_APPLICATION_NODE_INFORMATION-3]
	_ = x[SET_APPLICATION_NODE_INFORMATION_COMMAND_CLASSES-12]
	_ = x[GET_CONTROLLER_CAPABILITIES-5]
	_ = x[GET_CAPABILITIES-7]
	_ = x[GET_LONG_RANGE_NODES-218]
	_ = x[GET_ZWAVE_LONG_RANGE_CHANNEL-219]
	_ = x[SET_ZWAVE_LONG_RANGE_CHANNEL-220]
	_ = x[GET_PROTOCOL_VERSION-9]
	_ = x[GET_LIBRARY-189]
	_ = x[SOFT_RESET-8]
	_ = x[SET_DEFAULT-66]
	_ = x[SETUP_ZWAVE_API-11]
	_ = x[NOP-233]
	_ = x[GET_NODE_INFORMATION_PROTOCOL_DATA-65]
	_ = x[SEND_NODE_INFORMATION-18]
	_ = x[REQUEST_NODE_INFORMATION-96]
	_ = x[SET_LEARN_MODE-80]
}

const _CommandID_name = "GET_INIT_DATASET_APPLICATION_NODE_INFORMATIONGET_CONTROLLER_CAPABILITIESGET_CAPABILITIESSOFT_RESETGET_PROTOCOL_VERSIONSETUP_ZWAVE_APISET_APPLICATION_NODE_INFORMATION_COMMAND_CLASSESSEND_NODE_INFORMATIONGetLibraryVersionGET_NODE_INFORMATION_PROTOCOL_DATASET_DEFAULTSET_LEARN_MODEREQUEST_NODE_INFORMATIONGET_LIBRARYGET_LONG_RANGE_NODESGET_ZWAVE_LONG_RANGE_CHANNELSET_ZWAVE_LONG_RANGE_CHANNELNOP"

var _CommandID_map = map[CommandID]string{
	2:   _CommandID_name[0:13],
	3:   _CommandID_name[13:45],
	5:   _CommandID_name[45:72],
	7:   _CommandID_name[72:88],
	8:   _CommandID_name[88:98],
	9:   _CommandID_name[98:118],
	11:  _CommandID_name[118:133],
	12:  _CommandID_name[133:181],
	18:  _CommandID_name[181:202],
	21:  _CommandID_name[202:219],
	65:  _CommandID_name[219:253],
	66:  _CommandID_name[253:264],
	80:  _CommandID_name[264:278],
	96:  _CommandID_name[278:302],
	189: _CommandID_name[302:313],
	218: _CommandID_name[313:333],
	219: _CommandID_name[333:361],
	220: _CommandID_name[361:389],
	233: _CommandID_name[389:392],
}

func (i CommandID) String() string {
	if str, ok := _CommandID_map[i]; ok {
		return str
	}
	return "CommandID(" + strconv.FormatInt(int64(i), 10) + ")"
}
