// Code generated by "stringer -type=LibraryType"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StaticControllerLibrary-1]
	_ = x[PortableControllerLibrary-2]
	_ = x[Enhanced232EndNodeLibrary-3]
	_ = x[EndNodeLibrary-4]
	_ = x[InstallerLibrary-5]
	_ = x[RoutingEndNodeLibrary-6]
	_ = x[BridgeControllerLibrary-7]
}

const _LibraryType_name = "StaticControllerLibraryPortableControllerLibraryEnhanced232EndNodeLibraryEndNodeLibraryInstallerLibraryRoutingEndNodeLibraryBridgeControllerLibrary"

var _LibraryType_index = [...]uint8{0, 23, 48, 73, 87, 103, 124, 147}

func (i LibraryType) String() string {
	i -= 1
	if i >= LibraryType(len(_LibraryType_index)-1) {
		return "LibraryType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LibraryType_name[_LibraryType_index[i]:_LibraryType_index[i+1]]
}
