// Code generated by "stringer -type=state"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateBeginFrame-0]
	_ = x[stateLength-1]
	_ = x[stateCommandType-2]
	_ = x[stateCommandID-3]
	_ = x[statePayload-4]
	_ = x[stateEndPayload-5]
}

const _state_name = "stateBeginFramestateLengthstateCommandTypestateCommandIDstatePayloadstateEndPayload"

var _state_index = [...]uint8{0, 15, 26, 42, 56, 68, 83}

func (i state) String() string {
	if i < 0 || i >= state(len(_state_index)-1) {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
