// Code generated by "stringer -type=TransmissionOption"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TRANSMIT_OPTION_ACK-0]
	_ = x[TRANSMIT_OPTION_LOW_POWER-1]
	_ = x[TRANSMIT_OPTION_AUTO_ROUTE-2]
	_ = x[TRANSMIT_OPTION_NO_ROUTE-4]
	_ = x[TRANSMIT_OPTION_EXPLORE-5]
}

const (
	_TransmissionOption_name_0 = "TRANSMIT_OPTION_ACKTRANSMIT_OPTION_LOW_POWERTRANSMIT_OPTION_AUTO_ROUTE"
	_TransmissionOption_name_1 = "TRANSMIT_OPTION_NO_ROUTETRANSMIT_OPTION_EXPLORE"
)

var (
	_TransmissionOption_index_0 = [...]uint8{0, 19, 44, 70}
	_TransmissionOption_index_1 = [...]uint8{0, 24, 47}
)

func (i TransmissionOption) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _TransmissionOption_name_0[_TransmissionOption_index_0[i]:_TransmissionOption_index_0[i+1]]
	case 4 <= i && i <= 5:
		i -= 4
		return _TransmissionOption_name_1[_TransmissionOption_index_1[i]:_TransmissionOption_index_1[i+1]]
	default:
		return "TransmissionOption(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
